### ISSUE TITLE
Illustrasjoner og filer for dokumentasjonen

### ISSUE THREAD

**Issue by steibrun** [ks-no/svarut-dokumentasjon#1]
![forsendelsestatusoversikt](https://cloud.githubusercontent.com/assets/7090712/12776463/70a64fd2-ca56-11e5-8d31-8696824b8df1.png)

**Comment by steibrun** [comment]
[java-eksempel.zip](https://github.com/ks-no/svarut-dokumentasjon/files/121358/java-eksempel.zip)

**Comment by steibrun** [comment]
[dot-net-eksempel.zip](https://github.com/ks-no/svarut-dokumentasjon/files/121363/dot-net-eksempel.zip)

**Comment by steibrun** [comment]
[kodeeksempel-mottaker-rest.zip](https://github.com/ks-no/svarut-dokumentasjon/files/121367/kodeeksempel-mottaker-rest.zip)

**Comment by steibrun** [comment]
![svarutkomponenter](https://cloud.githubusercontent.com/assets/7090712/12882356/5e0b376c-ce51-11e5-81fb-680247bef0b7.png)

**Comment by steibrun** [comment]
![svarutintegrasjoner](https://cloud.githubusercontent.com/assets/7090712/12882407/a0981f28-ce51-11e5-87f0-b390681645da.png)

**Comment by steibrun** [comment]
![sikkerhet](https://cloud.githubusercontent.com/assets/7090712/13436862/95b77be8-dfe1-11e5-97e0-5d1e56a68512.png)

**Comment by audunmeltzer** [comment]
Dokumentasjon på svarut finner en her:
- http://www.ks.no/svarut/
- https://svarut.wordpress.com/
- https://ks-no.github.io/svarut/ 
- https://forvaltning.fiks.ks.no/sikkerhet-dokumentasjon/ros/svarut/
