### ISSUE TITLE
Savner eksempel for Dotnet Core 2

### ISSUE THREAD

**Issue by Hoaas** [ks-no/svarut-dokumentasjon#3]
Eller, savner støtte for noe annet enn MTOM, da dette ikke støttes i Dotnet Core 2, blir vel mer riktig å si.

https://github.com/dotnet/wcf/issues/1810

**Comment by idar** [comment]
Vi kan ikke bruke soap uten mtom, fordi det tar for mye cpu resurser å decode store filer i xml. Vi har lenge hatt en plan om et rest lignende api for innsending også. Dette kan prioriteres om behovet er stort.

Kan du sende en mail til svarut-utvikling@ks.no med litt info om hvilket system som trenger dette og størrelsen på bruken av det?
