### ISSUE TITLE
Hoveddokument? subsidiert: garantert rekkefølge?

### ISSUE THREAD

**Issue by sindrehauglum** [ks-no/svarut-dokumentasjon#4]
Behov: Å kunne angi et vedlegg som hoveddokument. 
Om  ikke det støttes så lurer vi på om dere garanterer rekkefølge på vedlegg?

**Comment by idar** [comment]
Det er ikke støtte for hvoeddokument, men det er første dokumentet hos alle som sender i dag.
rekkefølgen er garantert.
